app:
  name: myapp
  version: 1.0.0
  port: 8080

database:
  host: localhost
  port: 5432
  name: mydb
  user: admin
  password: secret

redis:
  host: localhost
  port: 6379
  db: 0

logging:
  level: info
  file: app.log 