name: CI Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Create source code archive
        run: |
          # 创建一个临时目录
          mkdir -p /tmp/release
          # 复制所有文件到临时目录（排除.git和.github）
          rsync -av --exclude='.git' --exclude='.github' . /tmp/release/
          # 从临时目录创建压缩包
          cd /tmp/release && tar -czf $GITHUB_WORKSPACE/conf2env-source.tar.gz .

      - name: Build binaries
        run: |
          VERSION=${{ github.ref_name }}
          LDFLAGS="-X main.Version=${VERSION} -s -w"
          
          # Linux
          GOOS=linux GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o conf2env-linux-amd64 ./cmd/conf2env
          GOOS=linux GOARCH=arm64 go build -ldflags="${LDFLAGS}" -o conf2env-linux-arm64 ./cmd/conf2env
          
          # macOS
          GOOS=darwin GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o conf2env-darwin-amd64 ./cmd/conf2env
          GOOS=darwin GOARCH=arm64 go build -ldflags="${LDFLAGS}" -o conf2env-darwin-arm64 ./cmd/conf2env
          
          # Windows
          GOOS=windows GOARCH=amd64 go build -ldflags="${LDFLAGS}" -o conf2env-windows-amd64.exe ./cmd/conf2env
          GOOS=windows GOARCH=arm64 go build -ldflags="${LDFLAGS}" -o conf2env-windows-arm64.exe ./cmd/conf2env
          
          # Create checksums
          sha256sum conf2env-* > checksums.txt

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            conf2env-source.tar.gz \
            conf2env-linux-amd64 \
            conf2env-linux-arm64 \
            conf2env-darwin-amd64 \
            conf2env-darwin-arm64 \
            conf2env-windows-amd64.exe \
            conf2env-windows-arm64.exe \
            checksums.txt \
            --target="master" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes